name: Caller Default

on:
  push:
    branches: [release, hotfix, main]
  pull_request:
    branches: [release, hotfix, main]
  workflow_dispatch:
  
jobs:
  pipeline:
    uses: demo-hell/reusable-pipelines/.github/workflows/sf-delta.yml@main
    secrets: inherit